import { FC } from "react";
import { useClassifierStore } from "../../store";
import { ImageError } from "../../types";
import styles from "./AdvancedMetrics.module.scss";

import Logs from "./components/Logs";
import MetricInfoItem, { IDatum } from "./components/MetricInfoItem";

interface IProps {
	downloading: boolean;
	onDownload?: Function;
	predict?: Function;
	errors?: ImageError[];
	logs: {
		[index: string]: any;
	};
	training?: number;
	labels?: string[];
}

/**
 * Calculates data for the "Data" section of the component.
 *
 * @param labels Array of labels used in the model.
 * @returns An array of objects representing the data for the section.
 */
const getData = (labels: string[] = []) => {
	const numOfLabels = labels.reduce(
		(obj, label) => ({
			...obj,
			[label]: (obj[label] || 0) + 1,
		}),
		{}
	);

	return Object.keys(numOfLabels).map((label) => {
		return {
			label,
			data: numOfLabels[label],
		};
	});
};

/**
 * Generates an array of error messages.
 *
 * @param errors List of errors that occurred when loading images.
 * @returns An array of error messages.
 */
const getErrors = (errors: ImageError[] = []) =>
	errors.map(({ file }, key) => (
		<p key={key} className={styles.error}>
			Error loading image: {`${file.path}/${file.file.name}`}
		</p>
	));

/**
 * Calculates the evaluation accuracy of the model.
 *
 * @param predictions Array of prediction objects generated by the model.
 * @returns The evaluation accuracy as a float.
 */

const getEvaluation = (predictions: any[]) => {
	if (predictions.length > 0) {
		return (
			predictions.reduce((sum, { prediction, label }) => sum + (prediction === label ? 1 : 0), 0) / predictions.length
		);
	}
	return null;
};

/**
 * Displays potentially useful information about the model, as well as potential errors when loading in foreign images.
 */
const AdvancedMetrics: FC<IProps> = ({ labels, onDownload, downloading, training, logs, errors }) => {
	const predictions = useClassifierStore((state) => state.predictions);

	const evaluation = getEvaluation(predictions);
	const accuracyData: IDatum[] = [
		{
			data: training ? `${Math.round(training * 100)}%` : "--",
			label: "Training",
		},
		{
			data: evaluation ? `${Math.round(evaluation * 100)}%` : "--",
			label: "Evaluation",
		},
	];

	return (
		<div className={styles.container}>
			<MetricInfoItem title="Model Data" data={getData(labels)} />
			<div className={styles.errors}>{errors && getErrors(errors)}</div>
			<MetricInfoItem title="Accuracy" data={accuracyData} />
			<div className={styles.footer}>
				<Logs logs={logs} />
				{onDownload && (
					<button disabled={downloading} onClick={() => onDownload()}>
						Download
					</button>
				)}
			</div>
		</div>
	);
};

export default AdvancedMetrics;
